# This is a basic workflow to help you get started with Actions
name: Build and publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dokken/jupyterbook ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: '0 8 * * 1'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dolfinx/lab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test notebooks in parallel
        run: |
          pip3 install jupyter nbconvert tqdm
          cd chapter1
          jupyter-nbconvert --to python fundamentals_code.ipynb
          mpirun -n 2 python3 fundamentals_code.py
          jupyter-nbconvert --to python membrane_code.ipynb
          mpirun -n 2 python3 membrane_code.py
          cd ../chapter2
          jupyter-nbconvert --to python diffusion_code.ipynb
          mpirun -n 2 python3 diffusion_code.py
          jupyter-nbconvert --to python heat_code.ipynb
          mpirun -n 2 python3 heat_code.py
          jupyter-nbconvert --to python linearelasticity_code.ipynb
          mpirun -n 2 python3 linearelasticity_code.py
          jupyter-nbconvert --to python nonlinpoisson_code.ipynb
          mpirun -n 2 python3 nonlinpoisson_code.py
          jupyter-nbconvert --to python ns_code1.ipynb
          mpirun -n 2 python3 ns_code1.py
          jupyter-nbconvert --to python ns_code2.ipynb
          mpirun -n 2 python3 ns_code2.py

      # Runs a single command using the runners shell
      - name: Build the book
        run: |
          pip3 install -U jupyter-book sphinxcontrib-bibtex==1.0.0
          jupyter-book build -W .

      # Pusb book to HTML to github pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html