# This is a basic workflow to help you get started with Actions
name: Build and publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dokken/jupyterbook ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: '0 8 * * 1'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dolfinx/lab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the book
        run: |
          pip3 install -U jupyter-book sphinxcontrib-bibtex==1.0.0
          jupyter-book build -W .
      # Pusb book to HTML to github pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html